// Generated by https://quicktype.io

export interface UsersResponse {
    id: number;
    name: string;
    username: string;
    email: string;
    address: Address;
    phone: string;
    website: string;
    company: Company;
}

export interface Address {
    street: string;
    suite: string;
    city: string;
    zipcode: string;
    geo: Geo;
}

export interface Geo {
    lat: string;
    lng: string;
}

export interface Company {
    name: string;
    catchPhrase: string;
    bs: string;
}

export interface SimpleUsers {
    id: number;
    name: string;
    username: string;
    picture?: string;
    publications?: PostResponse[];
    loggedImageUser: string;
    likes?: number,
    isLiked?: boolean,
}

export interface PostResponse {
    userId: number;
    id: number;
    title: string;
    body: string;
    imagenPublicacion?: string;
}
